# Example of a pod using a service account , a service account allows 
# services like jenkins to connect to the cluster
apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccountName: dashboard-sa
