#Example of pod with a config map
apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod

spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
      - configMapRef:
          name: app-config # this will grab the lables from the config map named app-config
    