# A pod using a command and a restart policy
apiVersion: v1

kind: Pod

metadata:
  name: math-pod

spec:
  containers:
    - name: math-pod
      image: ubuntu
      command: ['expr', '3', '+', '2']
  restartPolicy: Never
