# A pod using a command and a restart policy, a restart policy is used
# to tell the pod wether it can restart when done, not to restart or restart
# on failure.
apiVersion: v1

kind: Pod

metadata:
  name: math-pod

spec:
  containers:
    - name: math-pod
      image: ubuntu
      command: ['expr', '3', '+', '2']
  restartPolicy: Never
