# This is a pod with muliple conatiners
apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: log-agent-container
      image: log-agent
