# This is a pod with muliple conatiners
apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp

spec:
  containers:
  # ------- container 1 ---------
    - name: nginx-container
      image: nginx
  # ------- container 1 ---------

  # ------- container 2 ---------
    - name: log-agent-container
      image: log-agent
  # ------- container 2 ---------
