# Example of a pod using a secret
apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  namespace: dev
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - secretRef:
            name: app-secret # this pod uses labels from the secret called app-secret
