# A secret is used add personal encrypted data to a pod, a password as example 
apiVersion: v1

kind: Secret

metadata:
  name: app-secret

data:
  DB_HOST: bXlzcWw= 
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ=
