# A replica set is similar to a replica controller but has a selector key decribed below
apiVersion: apps/v1

kind: ReplicaSet

metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end

spec:
  template:
  # ------- POD ---------
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  # ------- POD ---------
  replicas: 6
  selector: # the selector only selects pods that matches the 'matchLabels' label
    matchLabels:
      type: front-end